### ISSUE TITLE
必要数が分かりづらい

### ISSUE THREAD

**Issue by gaogao-9** [hexium310/priconne-memory-piece-checker#1]
所持数/必要数の表示は出来るが、結局の所メモピが足りているのか足りていないのかが分からない。

`所持数 - 必要数` のカラムを作り、足りてない場合には赤色文字、足りている場合には青色文字で表示させるとわかりやすそう。

**Comment by hexium310** [comment]
`所持数 - 必要数` のカラムを作りました。
提案ありがとうございます！
